export interface Recipe {
  id: string;
  name: string;
  category: 'iced_drink' | 'hot_drink' | 'specialty' | 'cloud' | 'brew_base' | 'syrup' | 'prep' | 'procedure';
  size?: string;
  steps: string[];
  notes?: string;
  decaf?: boolean;
  ingredients?: string[];
}

export const RECIPES: Recipe[] = [
  // ===================== ICED DRINKS =====================
  {
    id: 'jd1',
    name: 'Pure Tea (Iced)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['any tea', 'water', 'simple syrup', 'ice'],
    steps: [
      '150 mL any tea',
      'Add 100 mL cold water',
      'Add syrup (use half the sweetness %)',
      'Add ice',
    ],
  },
  {
    id: 'jd2',
    name: 'Oolong Milk Tea Boba',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['golden oolong', 'milk of choice', 'simple syrup', 'ice', 'brown sugar boba'],
    steps: [
      '150 mL golden oolong',
      'Add 100 mL milk of choice',
      'Add __ g simple syrup (amount per sweetness level)',
      'Add ice',
      'Add brown sugar boba',
    ],
    notes: 'Any other milk tea (not Ceylon) uses this same build: 150 mL tea + 100 mL milk of choice + simple syrup',
  },
  {
    id: 'jd2b',
    name: 'Milk Tea (Iced)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['ceylon tea', 'half n half', 'simple syrup', 'ice', 'brown sugar boba'],
    steps: [
      '200 mL Ceylon tea',
      'Add 50 mL half n half',
      'Add __ g simple syrup (amount per sweetness level)',
      'Add ice',
      'Add brown sugar boba',
    ],
  },
  {
    id: 'jd3',
    name: 'Matcha Jasmine Latte (Iced)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['matcha', 'jasmine house milk', 'magnolia jasmine tea', 'simple syrup', 'water', 'ice'],
    steps: [
      '100 mL water + 1 T. matcha into Breville',
      'In shaker: 100 mL jasmine milk',
      'Add 50 mL magnolia jasmine tea',
      'Add __ g simple syrup (amount per sweetness level) + ice',
      'Pour into cup',
      'Chill matcha with ice & pour on top',
    ],
  },
  {
    id: 'jd4',
    name: 'Brown Sugar Milk Tea Boba',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['ceylon tea', 'half n half', 'brown sugar syrup', 'ice', 'brown sugar boba'],
    steps: [
      '200 mL Ceylon tea',
      'Add 50 mL half n half',
      'Add __ g brown sugar syrup (amount per sweetness level)',
      'Add ice',
      'Add brown sugar boba',
    ],
  },
  {
    id: 'jd4e',
    name: 'Magnolia Jasmine Milk Tea Boba',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['magnolia jasmine tea', 'jasmine house milk', 'simple syrup', 'ice', 'brown sugar boba'],
    steps: [
      '150 mL magnolia jasmine tea',
      'Add 100 mL jasmine house milk',
      'Add __ g simple syrup (amount per sweetness level)',
      'Add ice',
      'Add brown sugar boba',
    ],
  },
  {
    id: 'jd4f',
    name: 'Caramel Milk Tea Boba',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['black house milk', 'caramel', 'ice', 'brown sugar boba'],
    steps: [
      '250 mL black milk',
      'Add 3 pumps caramel (75% sweetness)',
      'Add ice',
      'Add brown sugar boba',
    ],
  },
  {
    id: 'jd4b',
    name: 'Matcha Latte (Iced or Hot)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['matcha', 'milk', 'syrup', 'water', 'ice'],
    steps: [
      '100 mL water + 1 T. matcha into Breville',
      'In shaker: 150 mL milk',
      'Add __ g syrup (amount per sweetness level) + ice',
      'Pour into cup',
      'Chill matcha with ice & pour on top',
    ],
  },
  {
    id: 'jd4c',
    name: 'Taro Boba Bee (Taro Milk)',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['taro', 'milk', 'simple syrup', 'ice'],
    steps: [
      'Smear cup with taro & add topping',
      '250 mL milk',
      'Add 2 scoops taro',
      'Add __ g simple syrup (amount per sweetness level)',
      'Shake with ice',
    ],
  },
  {
    id: 'jd4d',
    name: 'Strawberry Fields (Matcha Cloud)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['strawberry pearls', 'whole milk', 'oat milk', 'strawberry syrup', 'matcha', 'foam base', 'vanilla syrup', 'ice'],
    steps: [
      'Strawberry pearls + ice in cup',
      'Add 100 mL whole milk',
      'Add 100 mL oat milk',
      'Pour 50 g strawberry syrup so it streaks down the sides',
      'Top with Matcha Cloud',
    ],
    notes: 'Matcha Cloud: 70 g foam base + ½ T. matcha + 15 g vanilla syrup, froth until thick',
  },
  {
    id: 'mt1',
    name: 'Matcha Lemonade',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['lemon', 'simple syrup', 'water', 'matcha', 'ice'],
    steps: [
      'Muddle 2-3 lemon pieces',
      'Add 50 g simple syrup',
      'Add 250 mL water',
      'Add ice',
      'Top with 100 mL chilled matcha',
    ],
  },
  {
    id: 'mt2',
    name: 'Matcha Bubble Tea',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['matcha', 'oat milk', 'brown sugar syrup', 'boba', 'water', 'ice'],
    steps: [
      '100 mL water + 1 T. matcha into Breville, then chill',
      'In shaker: 150 mL oat milk',
      'Add __ g brown sugar syrup (amount per sweetness level) + ice',
      'Add boba to cup',
      'Layer milk mixture, then matcha, into cup',
    ],
  },
  {
    id: 'mt3',
    name: 'Junmei Matcha Cloud Boba',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['black house milk', 'brown sugar syrup', 'boba', 'ice', 'salted matcha cloud'],
    steps: [
      '200 mL black milk',
      'Add __ g brown sugar syrup (amount per sweetness level)',
      'Add boba',
      'Add ice',
      'Top with Salted Matcha Cloud',
    ],
  },
  {
    id: 'mt4',
    name: 'Double Matcha Cloud',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['matcha', 'vanilla syrup', 'milk', 'ice', 'matcha cloud'],
    steps: [
      'Make a vanilla matcha latte (or flavor of choice)',
      'Add ice',
      'Top with Matcha Cloud',
    ],
  },
  {
    id: 'mt5',
    name: 'Sparkling Berry Matcha Cloud',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['strawberry syrup', 'sparkling water', 'ice', 'matcha cloud'],
    steps: [
      'Make a strawberry Italian soda',
      'Top with Matcha Cloud',
    ],
  },
  {
    id: 'mt6',
    name: 'Tokyo Fog',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['earl grey', 'whole milk', 'vanilla syrup', 'ice', 'salted matcha cloud'],
    steps: [
      '150 mL earl grey tea',
      'Add 150 mL whole milk',
      'Add 40 g vanilla syrup',
      'Add ice & top with Salted Matcha Cloud',
    ],
  },
  {
    id: 'jd5',
    name: 'Chai Latte (Iced)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['chai concentrate', 'half n half', 'vanilla syrup', 'brown sugar syrup', 'ice'],
    steps: [
      '200 mL chai concentrate',
      'Add 100 mL half n half',
      'Add 25 g vanilla syrup',
      'Add 25 g brown sugar syrup',
      'Add ice',
    ],
  },
  {
    id: 'jd6',
    name: 'London Fog (Iced) / Earl Grey Latte (Iced)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['earl grey', 'whole milk', 'vanilla syrup', 'ice'],
    steps: [
      '150 mL earl grey tea',
      'Add 150 mL whole milk',
      'Add 40 g vanilla syrup',
      'Add ice',
    ],
  },
  {
    id: 'jd7',
    name: 'Thai Tea Boba (Thai Iced Tea)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['thai tea', 'thai cream', 'vanilla syrup', 'ice', 'brown sugar boba'],
    steps: [
      '200 mL Thai tea concentrate',
      'Add 100 mL Thai cream',
      'Add 25 g vanilla syrup',
      'Add ice',
      'Add brown sugar boba',
    ],
    notes: 'Thai cream = 2 cups cream + ½ cup sweetened condensed milk',
  },
  {
    id: 'jd8',
    name: 'Yuzu Arnold Palmer',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['lemon', 'yuzu syrup', 'simple syrup', 'magnolia jasmine tea', 'water', 'ice'],
    steps: [
      'Muddle 2-3 lemon pieces',
      'Add 1.5 pumps yuzu syrup + a splash of simple syrup',
      'Fill up to 200 mL with magnolia jasmine tea',
      'Add 100 mL cold water',
      'Add ice, shake & strain into ice in cup',
    ],
  },
  {
    id: 'jd8b',
    name: 'Butterfly Yuzu (Blue Yuzu Arnold Palmer)',
    category: 'iced_drink',
    size: '16oz',
    ingredients: ['lemon', 'yuzu syrup', 'simple syrup', 'butterfly pea flower tea', 'magnolia jasmine tea', 'water', 'ice'],
    steps: [
      'Muddle 2-3 lemon pieces',
      'Add 1.5 pumps yuzu + 20 g simple syrup',
      'Fill to 150 mL with butterfly pea flower tea',
      'Add 50 mL magnolia jasmine (or more butterfly pea for decaf)',
      'Add 100 mL cold water',
      'Add ice',
    ],
    notes: 'Decaf if you use all butterfly pea flower tea instead of magnolia jasmine',
  },
  {
    id: 'jd9',
    name: 'Boba Bee (Sweetened milk, no tea)',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['milk', 'syrup', 'strawberry puree', 'taro', 'boba', 'popping pearls', 'ice'],
    steps: [
      'Put topping in cup (smear cup with puree for strawberry/taro)',
      'Measure 250 mL milk',
      'Add 50 g syrup',
      'Shake with ice',
    ],
  },
  {
    id: 'jd10',
    name: 'Italian Soda',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['syrup', 'sparkling water', 'half n half', 'ice'],
    steps: [
      '25 or 50 g syrup of choice into cup',
      'Fill with ice',
      'Add sparkling water almost to the top',
      'Top with half n half',
    ],
  },
  {
    id: 'rf1',
    name: 'Lemonade',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['lemon', 'syrup', 'water', 'ice'],
    steps: [
      'Muddle 2-3 lemon pieces',
      'Add 50 g syrup (normal sweet)',
      'Fill to 300 mL with cold water',
      'Add ice',
    ],
  },
  {
    id: 'rf2',
    name: 'Mango Passion Fruit Lemonade',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['mango puree', 'passion fruit puree', 'lemon', 'water', 'ice'],
    steps: [
      'Add 20 g mango puree + 20 g passion fruit puree to shaker',
      'Muddle with 2-3 lemon pieces',
      'Fill to 300 mL with cold water',
      'Add ice',
    ],
  },
  {
    id: 'jd11',
    name: 'Blue Boba Bee (Butterfly Pea Flower Latte)',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['butterfly pea flower tea', 'vanilla syrup', 'half n half', 'thai cream', 'ice'],
    steps: [
      'Put topping in cup',
      'Add ice',
      'Fill ¾ full with butterfly pea flower tea',
      'Add 20 g vanilla syrup',
      'Add 50 mL half n half',
      'Add 50 mL Thai cream',
      'Add extra tea if there is room',
    ],
    notes: 'Brew tea: 1 cup dried butterfly pea flowers + 15 cups 208°F water, steep 5 min, strain, cool. Keeps 4 days refrigerated.',
  },
  {
    id: 'jd12',
    name: 'Butterfly Pea Flower Milk Tea',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['butterfly pea flower tea', 'brown sugar syrup', 'boba', 'half n half', 'ice'],
    steps: [
      'Scoop Brown Sugar boba into cup',
      'Add 1 scoop ice',
      'Squeeze in 1 T. Brown Sugar Syrup',
      'Add 1.5 cup butterfly pea flower tea',
      'Slowly pour in 0.5 cup half & half',
    ],
  },
  {
    id: 'jd13',
    name: 'Iced Butterfly Pea Flower Tea Latte',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['butterfly pea flower tea', 'half n half', 'sweetened condensed milk', 'vanilla extract', 'ice'],
    steps: [
      'BREW: 4 tsp butterfly pea flower in 1.5 cups 180\u00B0F water, steep 5 min',
      'Make sweet vanilla cream: 2/3 cup half & half + 2T sweetened condensed milk + 2 tsp vanilla extract',
      'Stir to mix',
      'Pour cooled tea into cup filled with ice',
      'Slowly pour in the vanilla sweet cream',
    ],
    notes: 'Sweet cream keeps 2 days in fridge. Tea keeps 4 days.',
  },
  {
    id: 'jd14',
    name: 'Butterfly Matcha Lemonade',
    category: 'specialty',
    size: '16oz',
    ingredients: ['lemon', 'simple syrup', 'butterfly pea flower tea', 'matcha', 'ice'],
    steps: [
      'Muddle 2-3 lemon pieces',
      'Add 50 g simple syrup',
      'Fill up to 200 mL with butterfly pea flower tea',
      'Add ice',
      'Top with 100 mL prepared chilled matcha',
    ],
    notes: 'Customers can stir before drinking',
  },
  {
    id: 'jd15',
    name: 'Butterfly Pea Flower Iced Tea Lemonade',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['butterfly pea flower tea', 'lemonade', 'lemon', 'ice'],
    steps: [
      'Fill cup with ice',
      'Pour 2/3 cup cold Lemonade',
      'Fill to top with cold butterfly pea flower tea',
    ],
    notes: 'For sliced lemons, line inside cup first then add ice',
  },
  {
    id: 'jd16',
    name: 'Chamomile Peach Iced Tea',
    category: 'iced_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['chamomile', 'peach juice', 'ice'],
    steps: [
      'TEA: 2 Tablespoons loose Chamomile in 1/2 cup 208\u00B0F water',
      'STEEP: 5 minutes covered',
      'ICE: 1 cup',
      'STRAIN: Pour chamomile tea over ice',
      'ADD: 2/3 cup Peach Juice',
      'STIR',
    ],
  },

  // ===================== HOT DRINKS =====================
  {
    id: 'jd20',
    name: 'Chai Latte (Hot)',
    category: 'hot_drink',
    size: '16oz',
    ingredients: ['chai concentrate', 'half n half', 'vanilla syrup', 'brown sugar syrup'],
    steps: [
      'Pour hot water into hot drink cup to warm it & add sleeve',
      '300 mL chai concentrate',
      'Add 150 mL half n half',
      'Add 20 g vanilla syrup',
      'Add 20 g brown sugar syrup',
      'Heat in Breville',
      'Dump hot water from cup, pour drink into the warmed cup & serve',
    ],
  },
  {
    id: 'jd21',
    name: 'London Fog (Hot)',
    category: 'hot_drink',
    size: '16oz',
    ingredients: ['earl grey tea', 'whole milk', 'vanilla syrup'],
    steps: [
      'Pour hot water into hot drink cup to warm it & add sleeve',
      '250 mL earl grey tea',
      'Add 200 mL whole milk',
      'Add 40 g vanilla syrup',
      'Heat in Breville',
      'Dump hot water from cup, pour drink into the warmed cup & serve',
    ],
  },
  {
    id: 'jd22',
    name: 'Earl Grey Hot Chocolate',
    category: 'hot_drink',
    size: '16oz',
    ingredients: ['earl grey', 'hot chocolate base', 'whole milk', 'cream', 'dark chocolate', 'brown sugar syrup'],
    steps: [
      'Pour 150 mL Earl Grey concentrate into drink shaker',
      'Add 100 mL Hot Chocolate Base (whole milk, cream + dark chocolate)',
      'Add 150 mL whole milk (or milk of choice)',
      'Pour into Breville & froth at 140\u00B0F',
      'Meanwhile, make brown sugar foam: 80g cream + 1 T. brown sugar syrup',
      'Pour hot chocolate into hot cup with sleeve & top with foam',
    ],
  },
  {
    id: 'jd23',
    name: 'Hot Rooibos Latte',
    category: 'hot_drink',
    decaf: true,
    size: '16oz',
    ingredients: ['rooibos', 'milk', 'honey', 'vanilla extract', 'cinnamon'],
    steps: [
      'BREW: 2 tsp rooibos leaves in 8oz 208\u00B0F water, steep 5 min',
      'STEAM: 1 cup milk with 1 tsp honey & 1/4 tsp vanilla extract in frother',
      'Pour tea in cup, top with steamed milk',
      'Garnish with cinnamon',
    ],
  },
  {
    id: 'jd24',
    name: 'Hot London Fog (Original Recipe)',
    category: 'hot_drink',
    size: '16oz',
    ingredients: ['earl grey', 'lavender', 'whole milk', 'brown sugar syrup', 'vanilla syrup'],
    steps: [
      'STEEP: 4 tsp Earl Grey + 1/2 tsp dried lavender (optional) in 1.5 cups 208\u00B0F water, 5 min',
      'FROTH: 1.5 cups whole milk in Breville at 104\u00B0F',
      'STRAIN tea into cup',
      'STIR in 1 T. brown sugar syrup + 2 tsp vanilla syrup',
      'TOP with steamed milk',
      'Garnish with dried lavender buds (optional)',
    ],
    notes: 'Variations: Victoria Fog (lavender tea), Cape Town Fog (rooibos), Tokyo Fog (matcha), Dublin Fog (Irish breakfast)',
  },
  // Hot Teas (simple steep recipes)
  { id: 'ht1', name: 'Hot Assam Tea', category: 'hot_drink', size: '16oz', steps: ['3 tsp loose Assam \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'] },
  { id: 'ht2', name: 'Hot Black Current Tea', category: 'hot_drink', size: '16oz', steps: ['4g loose Black Current \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 3-5 min covered'] },
  { id: 'ht3', name: 'Hot Butterfly Pea Flower Tea', category: 'hot_drink', size: '16oz', steps: ['3 tsp loose Butterfly Pea Flower \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], notes: 'Add lemon to turn purple', decaf: true },
  { id: 'ht4', name: 'Hot Ceylon Tea', category: 'hot_drink', size: '16oz', steps: ['3 tsp loose Ceylon \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'] },
  { id: 'ht5', name: 'Hot Chamomile Tea', category: 'hot_drink', size: '16oz', steps: ['2 Tbsp loose Chamomile \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true },
  { id: 'ht6', name: 'Hot Darjeeling Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Darjeeling \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 4 min covered'] },
  { id: 'ht7', name: 'Hot English Breakfast Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose English Breakfast \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 5 min covered'] },
  { id: 'ht8', name: 'Hot Ginger Peach Tea', category: 'hot_drink', size: '16oz', steps: ['4g loose Ginger Peach \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 3-5 min covered'] },
  { id: 'ht9', name: 'Hot Irish Breakfast Tea', category: 'hot_drink', size: '16oz', steps: ['1 tsp loose Irish Breakfast \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 4-5 min covered'] },
  { id: 'ht10', name: 'Hot Mango Black Tea', category: 'hot_drink', size: '16oz', steps: ['4g loose Mango Black \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 3-5 min covered'] },
  { id: 'ht11', name: 'Hot Passionfruit Tea', category: 'hot_drink', size: '16oz', steps: ['4g loose Passionfruit \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 3-5 min covered'] },
  { id: 'ht12', name: 'Hot Raspberry Fruit Tea', category: 'hot_drink', size: '16oz', steps: ['4g loose Raspberry Fruit \u2022 2 cups water \u2022 212\u00B0F \u2022 Steep 3-5 min covered'] },
  { id: 'ht13', name: 'Hot Rooibos Tea', category: 'hot_drink', size: '16oz', steps: ['3 tsp loose Rooibos \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true },
  // Additional Decaf Herbal Teas from Loose Leaf menu
  { id: 'ht14', name: 'Hot Chrysanthemum Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Chrysanthemum \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true },
  { id: 'ht15', name: 'Hot Earl Grey Bouquet Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Earl Grey Bouquet (rooibos blend) \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Rooibos base with rose petals, lavender, bergamot' },
  { id: 'ht16', name: 'Hot Feeling Good Flower Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Feeling Good Flower \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Chamomile, rose petals, orange peel, lavender' },
  { id: 'ht17', name: 'Hot Ginger Bear Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Ginger Bear \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Ginger, mango, lemongrass, orange, lavender over rooibos' },
  { id: 'ht18', name: 'Hot Hibiscus Sunrise Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Hibiscus Sunrise \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Cinnamon, hibiscus, elderberries, cardamom, rose petals' },
  { id: 'ht19', name: 'Hot Lavender Mint Dark Chocolate Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Lavender Mint Dark Chocolate \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true },
  { id: 'ht20', name: 'Hot Lemon Silk Tea (Rooibos)', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Lemon Silk \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Lemongrass, honeybush, lemon balm over rooibos' },
  { id: 'ht21', name: 'Hot Mountain Berry Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Mountain Berry \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Blueberries, honeybush, bananas, cherries, hibiscus' },
  { id: 'ht22', name: 'Hot Sweet Peace Tea', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Sweet Peace \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Chamomile, spearmint, orange' },
  { id: 'ht23', name: 'Hot Vanilla Cream Tea (Rooibos)', category: 'hot_drink', size: '16oz', steps: ['2 tsp loose Vanilla Cream \u2022 2 cups water \u2022 208\u00B0F \u2022 Steep 5 min covered'], decaf: true, notes: 'Vanilla, honeybush, elder flowers over rooibos' },

  // ===================== SPECIALTY =====================
  {
    id: 'sp1',
    name: 'Matcha Shamrock Shake',
    category: 'specialty',
    size: '16oz',
    ingredients: ['matcha', 'whole milk', 'vanilla ice cream', 'mint extract', 'foam base', 'simple syrup', 'ice'],
    steps: [
      '150 mL whole milk + 350 mL vanilla ice cream into blender',
      'Add 1 T. Matcha powder',
      'Pulse blender',
      'Add 1 scoop ice + 1/8 tsp mint extract',
      'Blend until smooth & pour into cup',
      'Top with sweet cold foam (80g foam base + 30g simple syrup)',
    ],
  },
  {
    id: 'sp2',
    name: 'Mango Slush',
    category: 'specialty',
    decaf: true,
    size: '16oz',
    ingredients: ['frozen mango', 'mango nectar', 'simple syrup', 'lime', 'ice'],
    steps: [
      '300 mL frozen mango',
      '150 mL mango nectar',
      '50 g simple syrup',
      '1 scoop ice',
      'Squeeze juice from 1 lime wedge',
      'Blend until smooth & serve',
    ],
  },
  {
    id: 'sp3',
    name: 'Taro Shake',
    category: 'specialty',
    ingredients: ['taro', 'ice cream', 'milk', 'taro paste', 'ice'],
    steps: [
      '3 scoops of ice cream',
      '1 scoop of ice',
      '2 tbsp of taro',
      '150 mL of milk',
      'Blend',
      'Smear taro paste on cup',
    ],
  },
  {
    id: 'cl1',
    name: 'Berry Honey Oolong Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['golden oolong', 'milk', 'honey syrup', 'strawberry syrup', 'sea salt foam', 'ice'],
    steps: [
      '150 mL golden oolong',
      'Add 100 mL milk',
      'Add 10 g honey syrup',
      'Add 40 g strawberry syrup',
      'Top with sea salt foam',
    ],
  },
  {
    id: 'cl2',
    name: 'Brown Sugar Ceylon Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['ceylon tea', 'water', 'brown sugar syrup', 'sea salt foam', 'ice'],
    steps: [
      '150 mL Ceylon tea',
      'Add 100 mL cold water',
      'Add 35 g brown sugar',
      'Top with sea salt foam',
    ],
  },
  {
    id: 'cl3',
    name: 'Caramel Chai Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['chai concentrate', 'half n half', 'caramel', 'sea salt foam', 'ice'],
    steps: [
      '150 mL chai',
      'Add 100 mL half n half',
      'Add 3 pumps caramel',
      'Top with sea salt foam',
    ],
  },
  {
    id: 'cl4',
    name: 'London Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['earl grey', 'whole milk', 'vanilla syrup', 'honey lavender syrup', 'sea salt foam', 'ice'],
    steps: [
      '150 mL earl grey tea',
      'Add 150 mL whole milk',
      'Add 10 g vanilla syrup',
      'Add 25 g honey lavender syrup',
      'Top with sea salt foam',
    ],
  },
  {
    id: 'cl5',
    name: 'Magnolia Mango Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['magnolia jasmine tea', 'water', 'mango syrup', 'mango puree', 'sea salt foam', 'ice'],
    steps: [
      '150 mL magnolia jasmine tea',
      'Add 100 mL cold water',
      'Add 1 pump mango syrup',
      'Add 20 g mango puree',
      'Shake with ice',
      'Top with sea salt foam',
    ],
  },
  {
    id: 'cl6',
    name: 'Pumpkin Chai Cloud',
    category: 'cloud',
    size: '16oz',
    ingredients: ['chai concentrate', 'half n half', 'brown sugar syrup', 'vanilla syrup', 'pumpkin butter', 'sea salt foam', 'pumpkin pie spice', 'ice'],
    steps: [
      'In shaker: 150 mL chai + 100 mL half n half + 10 g brown sugar syrup + 10 g vanilla syrup + 2 scoops pumpkin butter',
      'Smear pumpkin butter inside the cup',
      'Add ice, then the chai mixture',
      'Top with sea salt foam',
      'Sprinkle pumpkin pie spice on top',
    ],
  },

  // ===================== BREW BASES =====================
  {
    id: 'bb1',
    name: 'Brew Base: Magnolia Jasmine Concentrate',
    category: 'brew_base',
    size: '2L weekdays / 3L weekends',
    steps: [
      'Weekdays: 2L of 175°F water + 25 g jasmine + 25 g magnolia loose leaves (50 g tea total, 50/50 split)',
      'Weekends: 3L of 175°F water + 37.5 g jasmine + 37.5 g magnolia loose leaves (75 g tea total, 50/50 split)',
      'Let tea brew for 8 minutes',
      'Pour through strainer into containers',
      'Place in ice bath, replace ice and stir frequently until cool',
      'Place in fridge. When open, pour into dispenser',
    ],
    notes: 'Same strength as the old 6L batch (25 g tea per liter), just smaller batches',
  },
  {
    id: 'bb2',
    name: 'Brew Base: Red Oolong Concentrate',
    category: 'brew_base',
    size: '2L weekdays / 3L weekends',
    steps: [
      'Weekdays: 2L of 212°F water + 50 g oolong loose leaves',
      'Weekends: 3L of 212°F water + 75 g oolong loose leaves',
      'Let tea brew for 10 minutes',
      'Pour through strainer into containers',
      'Place in ice bath, replace ice and stir frequently until cool',
      'Place in fridge. When open, pour into dispenser',
    ],
    notes: 'Same strength as the old 6L batch (25 g tea per liter), just smaller batches',
  },
  {
    id: 'bb3',
    name: 'Brew Base: Earl Grey Concentrate',
    category: 'brew_base',
    size: '2L weekdays / 3L weekends',
    steps: [
      'Weekdays: 2L of 200°F water + 50 g earl grey loose leaves',
      'Weekends: 3L of 200°F water + 75 g earl grey loose leaves',
      'Let tea brew for 7 minutes',
      'Pour through strainer into containers',
      'Place in ice bath, replace ice and stir frequently until cool',
      'Place in fridge. When open, pour into dispenser',
    ],
  },
  {
    id: 'bb4',
    name: 'Brew Base: Chai Syrup',
    category: 'brew_base',
    steps: [
      '10 cups water + 8 tbsp loose chai (or 5 sachets) + 1 1/3 cups sugar',
      'Bring water to boil. Turn off heat, steep tea 10 min',
      'Strain tea',
      'Rinse saucepan, pour strained tea back in',
      'Add sugar and simmer until dissolved while whisking',
      'Cool and store in fridge up to 5 days',
    ],
  },
  {
    id: 'bb5',
    name: 'Brew Base: Thai Tea',
    category: 'brew_base',
    size: '2.5L batch',
    steps: [
      '50g Thai Tea Mix + 50g Ceylon Tea + 150g Brown Sugar + 2.5L boiling water',
      'Combine in pot and steep for 5 minutes',
      'Strain out tea leaves and let cool 30 min',
      'Transfer to pitcher, store in fridge up to 4 days',
    ],
  },
  {
    id: 'bb6',
    name: 'Brew Base: Matcha Concentrate',
    category: 'brew_base',
    steps: [
      '700 mL water + 7 Tablespoons matcha powder',
      'Blend together',
      'Set in ice bath to cool',
      'Store in squeeze bottle & label',
    ],
  },
  {
    id: 'bb7',
    name: 'Brew Base: Butterfly Pea Flower Tea',
    category: 'brew_base',
    steps: [
      '1 cup dried butterfly pea flowers + 15 cups 208\u00B0F water',
      'Pour hot water over flowers',
      'Steep for 5 minutes',
      'Strain out flowers and let cool completely',
      'Store refrigerated up to 4 days',
    ],
  },
  {
    id: 'bb8',
    name: 'Cold Brew Assam Tea',
    category: 'brew_base',
    size: '64oz',
    steps: ['12 tsp loose Assam + 8 cups cold water \u2022 Steep 12 hours refrigerated'],
  },
  {
    id: 'bb9',
    name: 'Cold Brew Ceylon Tea',
    category: 'brew_base',
    size: '64oz',
    steps: ['12 tsp loose Ceylon + 8 cups cold water \u2022 Steep 12 hours refrigerated'],
  },
  {
    id: 'bb10',
    name: 'Cold Brew Chai Concentrate',
    category: 'brew_base',
    size: '12 servings',
    steps: [
      '12 tbsp loose Chai + 12 Tbsp sugar + 12 cups cold water',
      'Steep 12-24 hours refrigerated',
      'Strain & use within 3-4 days',
    ],
  },
  {
    id: 'bb11',
    name: 'House Milks',
    category: 'brew_base',
    size: '2L batch',
    steps: [
      'Use funnel to pour 50 g of tea into 2L of milk',
      'Let sit 8-12 hours in the fridge',
      'Pour milk through strainer into pitcher 3 times to remove all leaves',
      'Third time, pour into the infused milk container',
      'POUR OUT AFTER 24 HOURS',
    ],
  },
  {
    id: 'bb12',
    name: 'Make Boba',
    category: 'brew_base',
    steps: [
      'Boil 2L water from heater into rice cooker (3L weekends)',
      'Add 600g boba (1500g weekends), mix for 1 minute',
      'Set to cook for 30 minutes',
      'Set to keep warm for at least 30 minutes',
      'Pour boba into strainer and wash',
      'Put 300g honey or brown sugar into boba pot',
      'Add boba, mix with honey',
      'Put lid on, set pot to keep warm (too firm: set to 6, good texture: set to 3)',
    ],
    notes: 'Check regularly \u2014 if boba dries out, add more honey or syrup',
  },
  {
    id: 'bb13',
    name: 'Cream Cheese Mousse',
    category: 'brew_base',
    steps: [
      '300 mL heavy cream + 300g cream cheese + 300g sugar',
      'Heat cream in Breville',
      'Cheese and sugar in big syrup bowl',
      'Pour cream over cheese, mash with muddler until cheese melts',
      'Mix with blender',
      'Pour through sift',
      'Froth again until nice texture to float',
      'Pour into bottle',
    ],
  },
  {
    id: 'bb13b',
    name: 'Thai Cream Base',
    category: 'brew_base',
    steps: [
      '2 cups Cream + \u00BD cup sweetened condensed milk',
      'Mix together and store',
    ],
  },
  {
    id: 'bb14',
    name: 'Foam Base',
    category: 'brew_base',
    steps: [
      '2 cups Heavy Cream + 1 cup Whole Milk',
      'Mix together and store',
    ],
  },
  {
    id: 'bb15',
    name: 'Cold Foam',
    category: 'brew_base',
    steps: [
      '75 g foam base (up to 80 g)',
      'Add 2 T. syrup of choice (30 g)',
      'Froth until thick — do not over mix',
    ],
  },
  {
    id: 'bb15b',
    name: 'Matcha Cloud (Matcha Cold Foam)',
    category: 'brew_base',
    steps: [
      '70 g foam base',
      '½ Tablespoon matcha powder',
      '15 g vanilla syrup',
      'Froth until thick',
    ],
  },
  {
    id: 'bb15c',
    name: 'Salted Matcha Cloud',
    category: 'brew_base',
    steps: [
      '70 g foam base',
      '1 Tablespoon matcha powder',
      '15 g vanilla syrup',
      'Twist of pink salt',
      'Froth until thick',
    ],
  },
  {
    id: 'bb15d',
    name: 'Sea Salt Foam',
    category: 'brew_base',
    size: 'Batch',
    ingredients: ['heavy whipping cream', 'sweetened condensed milk', 'whole milk', 'sea salt'],
    steps: [
      '4 cups heavy whipping cream',
      '1 cup sweetened condensed milk',
      '8 Tablespoons milk of choice (whole milk)',
      '2 teaspoons sea salt',
      'Blend in the blender \u2014 CAUTION: do not overblend',
      'Stop when slightly thickened but still pourable',
    ],
    notes: 'Used to top all Salted Clouds',
  },
  {
    id: 'bb16',
    name: 'Make Sleeves',
    category: 'prep',
    steps: [
      'Hole punch the corners of the sleeves',
      'Run twine through the hole and make a firm knot',
      'Put a sticker on the sleeve',
    ],
  },

  // ===================== SYRUPS =====================
  {
    id: 'sy1',
    name: 'Simple Syrup',
    category: 'syrup',
    steps: [
      '6 cups water + 6 cups sugar',
      'Simmer on low heat, stirring until sugar dissolves',
      'Remove from heat & cool',
      'Store airtight in fridge up to 3 weeks',
    ],
  },
  {
    id: 'sy2',
    name: 'Simple Lemon Syrup',
    category: 'syrup',
    steps: [
      '2.5 cups lemon juice + 2.25 cups sugar + 3 tbsp lemon zest',
      'Simmer on low heat, stirring until sugar dissolves',
      'Remove from heat & cool',
      'Strain out zest with fine mesh sieve',
      'Store airtight in fridge up to 3 weeks',
    ],
  },
  {
    id: 'sy3',
    name: 'Vanilla Syrup',
    category: 'syrup',
    steps: [
      '5 cups water + 5 cups sugar',
      'Simmer on low heat, stirring until sugar dissolves',
      'Remove from heat & stir in 6 Tbsp vanilla extract',
      'Cool & store airtight in fridge up to 2 weeks',
    ],
  },
  {
    id: 'sy4',
    name: 'Honey Lavender Syrup',
    category: 'syrup',
    steps: [
      '3 cups honey + 3 cups water + 1.5 cups dried lavender + 2 small pinches pink salt',
      'Stir over medium-high heat until honey dissolves',
      'Bring to simmer then turn off heat',
      'Steep at least 20 min (longer = better)',
      'Strain out lavender flowers',
      'Store airtight in fridge up to 2 weeks',
    ],
  },
  {
    id: 'sy5',
    name: 'Honey Syrup',
    category: 'syrup',
    steps: [
      '4 cups honey + 2 cups hot water',
      'Pour honey into heat proof container, add hot water',
      'Stir until honey dissolves completely, let cool',
      'Store airtight in fridge up to 3 weeks',
    ],
  },
  {
    id: 'sy6',
    name: 'Brown Sugar Syrup',
    category: 'syrup',
    steps: [
      '6 cups brown sugar (packed) + 6 cups water + 3 tbsp vanilla extract',
      'Measure brown sugar into large metal bowl',
      'Pour boiling water over sugar, whisk until dissolved',
      'Add vanilla extract, stir to combine',
      'Cool 10 min, store in jar with lid in fridge',
    ],
    notes: 'Variations: Strong (add 6 tbsp molasses), Cinnamon (add 3 tsp), Nutmeg (add 3 tsp). For thicker: 1 part water to 2 parts sugar, simmer on stovetop.',
  },
  {
    id: 'sy7',
    name: 'Strawberry Syrup',
    category: 'syrup',
    steps: [
      '4 cups water + 3 cups white sugar + 5 cups strawberries (sliced)',
      'Boil 6 minutes on medium-high heat',
      'Mash strawberries with wooden spoon or potato masher while cooking',
      'Strain strawberry solids',
      'Pour syrup into airtight container',
      'Keeps up to 2 weeks refrigerated',
    ],
  },

  // ===================== PROCEDURES =====================
  {
    id: 'op1',
    name: 'Opening Procedures',
    category: 'procedure',
    steps: [
      'Turn on both AC units & fan to circulate air',
      'Heat water in boba maker',
      'IF COLD BREW STARTED LAST NIGHT: Remove tea leaves from milk by 9 AM',
      'Measure and cook boba when water boils (31 min cook, 31 min keep warm)',
      'Put water in boba warmer & heat brown sugar syrup and honey',
      'Finish straining the house milk',
      'Brew teas',
      'Make house syrups',
      'Wash boba and pour into hot storage',
      'Unlock the shop & take out chalkboard sign',
      'Set out pastries \u2014 cut samples into cupcake liners',
      'Set up chairs',
      'Refill straws',
      'Make cup sleeves',
      'Clean: wipe counters, fridge/freezer doors & handles, deep clean sinks, wipe walls',
    ],
  },
  {
    id: 'op2',
    name: 'Between Customers',
    category: 'procedure',
    steps: [
      'Check & make when needed:',
      '  \u2022 Foam Base',
      '  \u2022 Thai Cream',
      '  \u2022 Cream Cheese Mousse',
      '  \u2022 Chai Tea Syrup',
      '  \u2022 Thai Tea Base',
      '  \u2022 House Syrups',
      '  \u2022 Check Boba \u2014 too firm: keep on 6, too sticky: add syrup/water/ice, stir, set to 3',
      '  \u2022 Put stickers on cups',
      '  \u2022 Refill straws',
    ],
  },
  {
    id: 'op3',
    name: 'Closing Procedures',
    category: 'procedure',
    steps: [
      'IF COLD BREW STARTED: Remove tea leaves from milk (only 11-12 hours after start)',
      'Before locking door: wash anything you\'re done using',
      'If there is a lull, make cup sleeves',
      'Wrap cake in plastic wrap, put in fridge. Toss stale pastries',
      'Lock door, bring in chalkboard sign, wipe outdoor tables, close umbrellas',
      'After locking: wash dishes, mats, drink shakers, and boba pot',
      'Clean sink with soap and sponge',
      'Dump boba, dump teas/milks that are or will be 24+ hours old by opening',
      'Return syrups to original containers, wash syrup bottles',
      'Sundays: Water plants in food prep sink, leave to drain overnight',
      'Sundays: Clean floor drain by boba maker',
      'Wipe down all surfaces and counters',
      'Wipe down register and register screen',
      'Wipe down tables and put up chairs',
      'Make sure water heater has water',
      'If extra time: Prep tea leaves for opening shift',
      'LEAVE NOTE IF COLD BREW WAS STARTED',
      'Throw out boxes and trash',
      'Sweep/Vacuum',
      'Mop',
      'Turn off Air Conditioning',
      'Lock up',
    ],
  },
];

export function getRecipeCategories(): { id: string; label: string }[] {
  return [
    { id: 'iced_drink', label: 'Iced Drinks' },
    { id: 'hot_drink', label: 'Hot Drinks' },
    { id: 'specialty', label: 'Specialty' },
    { id: 'cloud', label: 'Salted Clouds' },
    { id: 'brew_base', label: 'Brew Bases & Prep' },
    { id: 'syrup', label: 'Syrups' },
    { id: 'prep', label: 'Prep' },
    { id: 'procedure', label: 'Procedures' },
  ];
}
